package cmj.dao;

import cmj.domain.BaseDict;
import cmj.domain.BaseDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int countByExample(BaseDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int deleteByExample(BaseDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int deleteByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int insert(BaseDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int insertSelective(BaseDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    List<BaseDict> selectByExample(BaseDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    BaseDict selectByPrimaryKey(String dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int updateByExampleSelective(@Param("record") BaseDict record, @Param("example") BaseDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int updateByExample(@Param("record") BaseDict record, @Param("example") BaseDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int updateByPrimaryKeySelective(BaseDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_dict
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    int updateByPrimaryKey(BaseDict record);

    List<BaseDict> selectDictTypeName(String id);
    List<BaseDict> selectDictSource(String id);
    List<BaseDict> selectDictSort(String id);
}