package cmj.domain;

public class BaseDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_type_code
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String dictTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_type_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String dictTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_item_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String dictItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_item_code
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String dictItemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_sort
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private Integer dictSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_enable
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String dictEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_dict.dict_memo
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String dictMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_id
     *
     * @return the value of base_dict.dict_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_id
     *
     * @param dictId the value for base_dict.dict_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_type_code
     *
     * @return the value of base_dict.dict_type_code
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getDictTypeCode() {
        return dictTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_type_code
     *
     * @param dictTypeCode the value for base_dict.dict_type_code
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictTypeCode(String dictTypeCode) {
        this.dictTypeCode = dictTypeCode == null ? null : dictTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_type_name
     *
     * @return the value of base_dict.dict_type_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getDictTypeName() {
        return dictTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_type_name
     *
     * @param dictTypeName the value for base_dict.dict_type_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictTypeName(String dictTypeName) {
        this.dictTypeName = dictTypeName == null ? null : dictTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_item_name
     *
     * @return the value of base_dict.dict_item_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getDictItemName() {
        return dictItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_item_name
     *
     * @param dictItemName the value for base_dict.dict_item_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictItemName(String dictItemName) {
        this.dictItemName = dictItemName == null ? null : dictItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_item_code
     *
     * @return the value of base_dict.dict_item_code
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getDictItemCode() {
        return dictItemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_item_code
     *
     * @param dictItemCode the value for base_dict.dict_item_code
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictItemCode(String dictItemCode) {
        this.dictItemCode = dictItemCode == null ? null : dictItemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_sort
     *
     * @return the value of base_dict.dict_sort
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public Integer getDictSort() {
        return dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_sort
     *
     * @param dictSort the value for base_dict.dict_sort
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictSort(Integer dictSort) {
        this.dictSort = dictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_enable
     *
     * @return the value of base_dict.dict_enable
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getDictEnable() {
        return dictEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_enable
     *
     * @param dictEnable the value for base_dict.dict_enable
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictEnable(String dictEnable) {
        this.dictEnable = dictEnable == null ? null : dictEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_dict.dict_memo
     *
     * @return the value of base_dict.dict_memo
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getDictMemo() {
        return dictMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_dict.dict_memo
     *
     * @param dictMemo the value for base_dict.dict_memo
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setDictMemo(String dictMemo) {
        this.dictMemo = dictMemo == null ? null : dictMemo.trim();
    }
}