package cmj.domain;

import java.util.Date;

public class Customer {


    @Override
    public String toString() {
        return "Customer{" +
                "start=" + start +
                ", rows=" + rows +
                ", custId=" + custId +
                ", custName='" + custName + '\'' +
                ", custUserId=" + custUserId +
                ", custCreateId=" + custCreateId +
                ", custSource='" + custSource + '\'' +
                ", custIndustry='" + custIndustry + '\'' +
                ", custLevel='" + custLevel + '\'' +
                ", custLinkman='" + custLinkman + '\'' +
                ", custPhone='" + custPhone + '\'' +
                ", custMobile='" + custMobile + '\'' +
                ", custZipcode='" + custZipcode + '\'' +
                ", custAddress='" + custAddress + '\'' +
                ", custCreatetime=" + custCreatetime +
                '}';
    }

    private Integer start;

    private Integer rows;

    public Integer getStart() {
        return start;
    }

    public void setStart(Integer start) {
        this.start = start;
    }

    public Integer getRows() {
        return rows;
    }

    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private Integer custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_user_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private Integer custUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_create_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private Integer custCreateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_source
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_industry
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_level
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_linkman
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custLinkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_phone
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_mobile
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_zipcode
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custZipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_address
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private String custAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.cust_createtime
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    private Date custCreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_id
     *
     * @return the value of customer.cust_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public Integer getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_id
     *
     * @param custId the value for customer.cust_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_name
     *
     * @return the value of customer.cust_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_name
     *
     * @param custName the value for customer.cust_name
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_user_id
     *
     * @return the value of customer.cust_user_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public Integer getCustUserId() {
        return custUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_user_id
     *
     * @param custUserId the value for customer.cust_user_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustUserId(Integer custUserId) {
        this.custUserId = custUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_create_id
     *
     * @return the value of customer.cust_create_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public Integer getCustCreateId() {
        return custCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_create_id
     *
     * @param custCreateId the value for customer.cust_create_id
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustCreateId(Integer custCreateId) {
        this.custCreateId = custCreateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_source
     *
     * @return the value of customer.cust_source
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustSource() {
        return custSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_source
     *
     * @param custSource the value for customer.cust_source
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustSource(String custSource) {
        this.custSource = custSource == null ? null : custSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_industry
     *
     * @return the value of customer.cust_industry
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustIndustry() {
        return custIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_industry
     *
     * @param custIndustry the value for customer.cust_industry
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustIndustry(String custIndustry) {
        this.custIndustry = custIndustry == null ? null : custIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_level
     *
     * @return the value of customer.cust_level
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustLevel() {
        return custLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_level
     *
     * @param custLevel the value for customer.cust_level
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustLevel(String custLevel) {
        this.custLevel = custLevel == null ? null : custLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_linkman
     *
     * @return the value of customer.cust_linkman
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustLinkman() {
        return custLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_linkman
     *
     * @param custLinkman the value for customer.cust_linkman
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustLinkman(String custLinkman) {
        this.custLinkman = custLinkman == null ? null : custLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_phone
     *
     * @return the value of customer.cust_phone
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustPhone() {
        return custPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_phone
     *
     * @param custPhone the value for customer.cust_phone
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustPhone(String custPhone) {
        this.custPhone = custPhone == null ? null : custPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_mobile
     *
     * @return the value of customer.cust_mobile
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustMobile() {
        return custMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_mobile
     *
     * @param custMobile the value for customer.cust_mobile
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustMobile(String custMobile) {
        this.custMobile = custMobile == null ? null : custMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_zipcode
     *
     * @return the value of customer.cust_zipcode
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustZipcode() {
        return custZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_zipcode
     *
     * @param custZipcode the value for customer.cust_zipcode
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustZipcode(String custZipcode) {
        this.custZipcode = custZipcode == null ? null : custZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_address
     *
     * @return the value of customer.cust_address
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public String getCustAddress() {
        return custAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_address
     *
     * @param custAddress the value for customer.cust_address
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustAddress(String custAddress) {
        this.custAddress = custAddress == null ? null : custAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.cust_createtime
     *
     * @return the value of customer.cust_createtime
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public Date getCustCreatetime() {
        return custCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.cust_createtime
     *
     * @param custCreatetime the value for customer.cust_createtime
     *
     * @mbggenerated Sun Apr 26 14:06:39 CST 2020
     */
    public void setCustCreatetime(Date custCreatetime) {
        this.custCreatetime = custCreatetime;
    }
}